### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by FLEXXISHERE** [Lynnette177/Battle.net-Account-Generator#1]
C:\Users\AbdulWasay\Downloads\Battle.net-Account-Generator-main\Battle.net-Account-Generator-main>py 5simver.py
Accounts to make: 1
Exception in thread Thread-1 (create_account):
Traceback (most recent call last):
  File "C:\Program Files\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\AbdulWasay\Downloads\Battle.net-Account-Generator-main\Battle.net-Account-Generator-main\5simver.py", line 164, in create_account
    browser = playwright.firefox.launch(headless=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AbdulWasay\AppData\Roaming\Python\Python311\site-packages\playwright\sync_api\_generated.py", line 14882, in launch
    self._sync(
  File "C:\Users\AbdulWasay\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "C:\Users\AbdulWasay\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_browser_type.py", line 94, in launch
    Browser, from_channel(await self._channel.send("launch", params))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AbdulWasay\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_connection.py", line 63, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AbdulWasay\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_connection.py", line 495, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\AbdulWasay\AppData\Roaming\Python\Python311\site-packages\playwright\_impl\_connection.py", line 101, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._errors.Error: Executable doesn't exist at C:\Users\AbdulWasay\AppData\Local\ms-playwright\firefox-1438\firefox\firefox.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝

**Comment by Lynnette177** [comment]
run playwright install command

**Comment by FLEXXISHERE** [comment]
not working

**Comment by Lynnette177** [comment]
If you can't even manage to run playwright I suggest you to give up
